export const LANDING = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const PASSWORD_FORGET = '/password-forget'
export const HOME = '/home'
export const ACCOUNT = '/account'
